// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGFCWUcFRclD83tcteHHqQUkECOyOHWo',
    appId: '1:931551255115:web:2f8670a3b96ebcc5590bce',
    messagingSenderId: '931551255115',
    projectId: 'flutter-auth-c97e3',
    authDomain: 'flutter-auth-c97e3.firebaseapp.com',
    storageBucket: 'flutter-auth-c97e3.firebasestorage.app',
    measurementId: 'G-GWGPLNSP18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DW_tgC03J_CuXTDDTe7ImHImTQ9RNqE',
    appId: '1:931551255115:android:6c22234347883076590bce',
    messagingSenderId: '931551255115',
    projectId: 'flutter-auth-c97e3',
    storageBucket: 'flutter-auth-c97e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQ0BIcoIMiVOMLOS2mMhP61OGR75Nc6s',
    appId: '1:931551255115:ios:30445be843b4125c590bce',
    messagingSenderId: '931551255115',
    projectId: 'flutter-auth-c97e3',
    storageBucket: 'flutter-auth-c97e3.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQ0BIcoIMiVOMLOS2mMhP61OGR75Nc6s',
    appId: '1:931551255115:ios:30445be843b4125c590bce',
    messagingSenderId: '931551255115',
    projectId: 'flutter-auth-c97e3',
    storageBucket: 'flutter-auth-c97e3.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpGFCWUcFRclD83tcteHHqQUkECOyOHWo',
    appId: '1:931551255115:web:20833cd71d858bd6590bce',
    messagingSenderId: '931551255115',
    projectId: 'flutter-auth-c97e3',
    authDomain: 'flutter-auth-c97e3.firebaseapp.com',
    storageBucket: 'flutter-auth-c97e3.firebasestorage.app',
    measurementId: 'G-1M51GY4E43',
  );
}
